# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-01 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('image', models.FileField(upload_to='uploads/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blood_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB', 'AB - Universal Recipient'), ('O+', 'O+ - Universal Donor'), ('A-', 'A-'), ('B-', 'B-'), ('O-', 'O-')], default='O', help_text='What blood group are you?', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('CM', 'Cameroon'), ('EG', 'Equetorial Guinnea'), ('USA', 'United States')], help_text='PLease enter country of origin', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(choices=[('MBH', 'Mbingo Baptist Hospital (MBH)'), ('BBH', 'Banso Baptist Hospital (BBH)')], help_text='Hospital of/for blood examination', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('NW', 'North-West'), ('SW', 'South-West'), ('LT', 'Littoral')], help_text='Region of origin', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='blood_client',
            name='blood_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.Blood_Group'),
        ),
        migrations.AddField(
            model_name='blood_client',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.Country'),
        ),
        migrations.AddField(
            model_name='blood_client',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.Hospital'),
        ),
        migrations.AddField(
            model_name='blood_client',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.Region'),
        ),
    ]
