# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-01 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0004_auto_20170702_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved',
            name='approved',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5),
        ),
        migrations.AlterField(
            model_name='blood_client',
            name='approved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blood.Approved'),
        ),
    ]
